language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-25
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-google-m2repository

before_script:
  - chmod +x gradlew

script:
  - ./gradlew clean build
