language: android

jdk:
  - oraclejdk8

android:
  components:
    - android-25
    - tools
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - gradle clean build
